[package]
name = "io-http"
description = "HTTP client library for Rust"
version = "0.4.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "no-std"]
keywords = ["io-free", "no-std", "coroutine", "socket", "http"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-http/latest/io_http"
repository = "https://github.com/pimalaya/io-http"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring"]
client = []
rustls-ring = ["client", "pimalaya-stream/rustls-ring", "dep:anyhow", "dep:pimalaya-stream"]
rustls-aws = ["client", "pimalaya-stream/rustls-aws", "dep:anyhow", "dep:pimalaya-stream"]
native-tls = ["client", "pimalaya-stream/native-tls", "dep:anyhow", "dep:pimalaya-stream"]
vendored = ["pimalaya-stream?/vendored"]

[[example]]
name = "std_http10"
path = "examples/std_http10.rs"

[[example]]
name = "tokio_http11"
path = "examples/tokio_http11.rs"

[[example]]
name = "tokio_client"
path = "examples/tokio_client.rs"
required-features = ["client"]

[[example]]
name = "std_http11"
path = "examples/std_http11.rs"
required-features = ["rustls-ring"]

[dev-dependencies]
env_logger = "0.11"
rustls = { version = "0.23", default-features = false, features = ["logging", "ring", "std", "tls12"] }
rustls-platform-verifier = "0.7"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "ring", "tls12"] }
url = { version = "2.5", default-features = false }

[dependencies]
anyhow = { version = "1", optional = true }
base64 = { version = "0.23", default-features = false, features = ["alloc"] }
httparse = { version = "1.10", default-features = false }
log = { version = "0.4", default-features = false }
memchr = { version = "2.7", default-features = false }
pimalaya-stream = { version = "0.2", default-features = false, optional = true }
secrecy = { version = "0.10", default-features = false }
thiserror = { version = "2", default-features = false }
url = { version = "2.5", default-features = false }
